# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoviesDB

	pod 'Alamofire', '~> 5.2'
	pod 'RxSwift', '~> 5'
    	pod 'RxCocoa', '~> 5'

end
